steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ubuntu-gnome-vnc:$SHORT_SHA', '.']
  dir: '/workspace/ubuntu-gnome-vnc/'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/ubuntu-gnome-vnc:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ubuntu-firefox:$SHORT_SHA', '.']
  dir: '/workspace/ubuntu-firefox/'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/ubuntu-firefox:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ubuntu-chrome:$SHORT_SHA', '.']
  dir: '/workspace/ubuntu-chrome/'
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/ubuntu-chrome:$SHORT_SHA"]
timeout: 800s