version: '3'
services:
  rdp-chrome:
    build: rdp-chrome/.
    privileged: true
    ports:
      - "3389:3389"
  freeciv-client:
    build: freeciv-client/.
    privileged: true
  xvnc4-chrome:
    build: xvnc4-chrome/.
    privileged: true
  ubuntu-chrome:
    build: ubuntu-chrome/.
    privileged: true
  ubuntu-firefox:
    build: ubuntu-firefox/.
    privileged: true
  ubuntu-gnome:
    build: ubuntu-gnome-vnc/.
    privileged: true
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
  guacamole:
    image: guacamole/guacamole
    depends_on:
    - guacd
    - mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOSTNAME: mysql
      GUACD_HOSTNAME: guacd
      MYSQL_DATABASE: guac
      MYSQL_USER: guac_user
      MYSQL_PASSWORD: password
    links:
    - guacd
  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root_pwd
       MYSQL_DATABASE: guac
       MYSQL_USER: guac_user
       MYSQL_PASSWORD: password
  mysql-bootstrap:
    build: mysql-bootstrap/.
    depends_on:
    - mysql
    environment:
      mysql_host: mysql
      mysql_db: guac
      mysql_user: guac_user
      mysql_pwd: password
