version: '3'
services:
  freeciv-client:
    build: freeciv-client/.
    privileged: true
  ubuntu-chrome:
    build: ubuntu-chrome/.
    privileged: true
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
  guacamole:
    image: guacamole/guacamole
    depends_on:
    - guacd
    - mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOSTNAME: mysql
      GUACD_HOSTNAME: guacd
      MYSQL_DATABASE: guac
      MYSQL_USER: guac_user
      MYSQL_PASSWORD: password
    links:
    - guacd
  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: root_pwd
       MYSQL_DATABASE: guac
       MYSQL_USER: guac_user
       MYSQL_PASSWORD: password
    volumes:
       - db_data:/var/lib/mysql
  mysql-bootstrap:
    build: mysql-bootstrap/.
    depends_on:
    - mysql
    environment:
      mysql_host: mysql
      mysql_db: guac
      mysql_user: guac_user
      mysql_pwd: password


volumes:
    db_data: {}
