apiVersion: v1
kind: Service
metadata:
  name: jatm-service
spec:
  selector:
    app: jatm-front-end
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jatm-lb
spec:
  backend:
    serviceName: jatm-service
    servicePort: 80